MATHEMATIQUE: Maths
FRANCAIS: Français
ANGLAIS: Anglais
HISTOIRE: Histoire Geo
PHYSIQUE: Physique Chimie
ESPAGNOL: Espagnol
ENSEIGN: Science
ED.PHYSIQUE: Sport
NUMERIQUE: Info
ENS. MORAL: EMC
ACCOMP.CHOIX ORIENT.: Orientation